import 'react-toastify/dist/ReactToastify.css';
import "./globals.css";

import Footer from "@/components/Footer";
import Header from "@/components/header/Header";
// @/ === ../ 
import type { Metadata } from "next";
import { ToastContainer } from 'react-toastify';
import localFont from "next/font/local";

// import { Inter, Noto_Kufi_Arabic } from "next/font/google";


// const inter = Inter({subsets: ["latin"]});
// const notoKufiArabic = Noto_Kufi_Arabic({subsets: ["arabic"] , weight: ["300", "500"]});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "CLOUD HOSTING",
  description: "Cloud Hosting Project Generated by Merna Mamdouh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        <ToastContainer theme='colored' position='top-center'/>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
// ${inter.className} or ${notoKufiArabic.className} put this in body className